on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Beforre'
        run: ls
      
      - uses:  actions/checkout@v3
      
      - name: 'Afterr'
        run: ls
